/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchBatchIdRouteImport } from './routes/batch.$batchId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as BatchBatchIdSubjectSubjectIdRouteImport } from './routes/batch.$batchId.subject.$subjectId'
import { Route as BatchBatchIdSubjectSubjectIdTopicTopicIdRouteImport } from './routes/batch.$batchId.subject.$subjectId.topic.$topicId'

const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdRoute = BatchBatchIdRouteImport.update({
  id: '/batch/$batchId',
  path: '/batch/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdSubjectSubjectIdRoute =
  BatchBatchIdSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => BatchBatchIdRoute,
  } as any)
const BatchBatchIdSubjectSubjectIdTopicTopicIdRoute =
  BatchBatchIdSubjectSubjectIdTopicTopicIdRouteImport.update({
    id: '/topic/$topicId',
    path: '/topic/$topicId',
    getParentRoute: () => BatchBatchIdSubjectSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/saved': typeof SavedRoute
  '/telegram': typeof TelegramRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/batch/$batchId': typeof BatchBatchIdRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/batch/$batchId/subject/$subjectId': typeof BatchBatchIdSubjectSubjectIdRouteWithChildren
  '/batch/$batchId/subject/$subjectId/topic/$topicId': typeof BatchBatchIdSubjectSubjectIdTopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/saved': typeof SavedRoute
  '/telegram': typeof TelegramRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/batch/$batchId': typeof BatchBatchIdRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/batch/$batchId/subject/$subjectId': typeof BatchBatchIdSubjectSubjectIdRouteWithChildren
  '/batch/$batchId/subject/$subjectId/topic/$topicId': typeof BatchBatchIdSubjectSubjectIdTopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/saved': typeof SavedRoute
  '/telegram': typeof TelegramRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/batch/$batchId': typeof BatchBatchIdRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/batch/$batchId/subject/$subjectId': typeof BatchBatchIdSubjectSubjectIdRouteWithChildren
  '/batch/$batchId/subject/$subjectId/topic/$topicId': typeof BatchBatchIdSubjectSubjectIdTopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/saved'
    | '/telegram'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/batch/$batchId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/batch/$batchId/subject/$subjectId'
    | '/batch/$batchId/subject/$subjectId/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/saved'
    | '/telegram'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/batch/$batchId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/batch/$batchId/subject/$subjectId'
    | '/batch/$batchId/subject/$subjectId/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/saved'
    | '/telegram'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/batch/$batchId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/batch/$batchId/subject/$subjectId'
    | '/batch/$batchId/subject/$subjectId/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SavedRoute: typeof SavedRoute
  TelegramRoute: typeof TelegramRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BatchBatchIdRoute: typeof BatchBatchIdRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId': {
      id: '/batch/$batchId'
      path: '/batch/$batchId'
      fullPath: '/batch/$batchId'
      preLoaderRoute: typeof BatchBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId/subject/$subjectId': {
      id: '/batch/$batchId/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/batch/$batchId/subject/$subjectId'
      preLoaderRoute: typeof BatchBatchIdSubjectSubjectIdRouteImport
      parentRoute: typeof BatchBatchIdRoute
    }
    '/batch/$batchId/subject/$subjectId/topic/$topicId': {
      id: '/batch/$batchId/subject/$subjectId/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/batch/$batchId/subject/$subjectId/topic/$topicId'
      preLoaderRoute: typeof BatchBatchIdSubjectSubjectIdTopicTopicIdRouteImport
      parentRoute: typeof BatchBatchIdSubjectSubjectIdRoute
    }
  }
}

interface BatchBatchIdSubjectSubjectIdRouteChildren {
  BatchBatchIdSubjectSubjectIdTopicTopicIdRoute: typeof BatchBatchIdSubjectSubjectIdTopicTopicIdRoute
}

const BatchBatchIdSubjectSubjectIdRouteChildren: BatchBatchIdSubjectSubjectIdRouteChildren =
  {
    BatchBatchIdSubjectSubjectIdTopicTopicIdRoute:
      BatchBatchIdSubjectSubjectIdTopicTopicIdRoute,
  }

const BatchBatchIdSubjectSubjectIdRouteWithChildren =
  BatchBatchIdSubjectSubjectIdRoute._addFileChildren(
    BatchBatchIdSubjectSubjectIdRouteChildren,
  )

interface BatchBatchIdRouteChildren {
  BatchBatchIdSubjectSubjectIdRoute: typeof BatchBatchIdSubjectSubjectIdRouteWithChildren
}

const BatchBatchIdRouteChildren: BatchBatchIdRouteChildren = {
  BatchBatchIdSubjectSubjectIdRoute:
    BatchBatchIdSubjectSubjectIdRouteWithChildren,
}

const BatchBatchIdRouteWithChildren = BatchBatchIdRoute._addFileChildren(
  BatchBatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SavedRoute: SavedRoute,
  TelegramRoute: TelegramRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BatchBatchIdRoute: BatchBatchIdRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
